### ISSUE TITLE
Only delete ".well-known/acme-challenge/"

### ISSUE THREAD

**Issue by jthomaschewski** [alexalouit/ISPConfig-letsencrypt#11]
In https://github.com/alexalouit/ISPConfig-letsencrypt/blob/ISPConfig-3.0.5.4p8/src/server/plugins-available/nginx_plugin.inc.php#L1133 the whole .well-known directory gets deleted.
It might contain other stuff - I think only  `/.well-known/acme-challenge` should be deleted.

For example Thunderbird auto configuration uses the path `/.well-known/autoconfig/mail/config-v1.1.xml`.

**Comment by alexalouit** [comment]
You're right, delete two directory and recreate it is nasty.
But at this time, Let's Encrypt has no clear position on how he creates the folders and challenge file, this is the only way for now to work all the time. (see https://github.com/letsencrypt/letsencrypt/commit/768c7cd9c09dc3161490934d3b69ace9c72937af).
