### ISSUE TITLE
Instructions to upgrade plugin

### ISSUE THREAD

**Issue by WKnak** [alexalouit/ISPConfig-letsencrypt#12]
What is the proper way to upgrade this project source and patch ISPConfig?

I found out by myself (wow) that `git pull` from inside the project folder will sync git repo, can I safelly run `php -q install.php` again?

**Comment by alexalouit** [comment]
Yes, re-run install, or install via manual installation and adjust `/etc/letsencrypt/cli.ini`.
With manual installation, the only thing to watch out is to remove the old entry from cronjob if is different. This is not the case currently.
