### ISSUE TITLE
Cant create certs for subdomains

### ISSUE THREAD

**Issue by Thumpxr** [alexalouit/ISPConfig-letsencrypt#15]
example websites in use:

website1.de
ab.website1.de

website1.de can use Letsencrypt
ab.website1.de gets the error: wrong cert and it shows me the cert for website1.de if i inspect it.

**Comment by alexalouit** [comment]
What is domain configuration, auto-subdomain field equal to wildcard?

**Comment by Thumpxr** [comment]
Domain: http://puu.sh/lQdUM/f735765b19.png
Subdomain: http://puu.sh/lQdUb/0d1d801120.png

Both setup as websites.
My subdomain list is empty.

**Comment by alexalouit** [comment]
Unfortunately, Let's Encrypt does not support (yet?) wildcard domain.
If you need only one subdomain, you must define the subdomain as domain, with "none" as auto-subdomain field.
Otherwise, if you need multiple subdomains in the same vhost, we can't do anything for the moment.

**Comment by Thumpxr** [comment]
Worked. Thanks.
