### ISSUE TITLE
The server experienced an internal error :: Error creating new authz

### ISSUE THREAD

**Issue by pixelquadrat** [alexalouit/ISPConfig-letsencrypt#17]
I installed your plug-in on my server and tried to get a certificate for a domain. 
But I don't get any certificate, because the LE-client ends with the error: 
The server experienced an internal error :: Error creating new authz

The full log-file is here: https://paste.ee/p/opqe6
(changed domain-name to example.com)

My Server:
Ubuntu 14.04
Apache 2.4
ISPConfig 3.0.5.4

**Comment by alexalouit** [comment]
Error don't come from your server/ispconfig, but from Let's Encrypt server.

Then, `acme-v01.api.letsencrypt.org` endpoint provide real certificat, I don't think example.com is in Let's Encrypt whitelist and dns authority domain pointing to your server.

For test and developpement, use `https://acme-staging.api.letsencrypt.org/directory`api endpoint.

**Comment by pixelquadrat** [comment]
No, I used a real domain (not example.com, just changed for the logfiles) and Let's Encrypt is now in public beta. So everyone can get a real certificate.
I already got several real certificates with the letsencrypt-auto client.

**Comment by alexalouit** [comment]
Check challenge file is accessible (create "by hand" file). If challenge directory work correctly, that's a Let's Encrypt issue.
