### ISSUE TITLE
Doesn't check for www.

### ISSUE THREAD

**Issue by blue-hound** [alexalouit/ISPConfig-letsencrypt#2]
The plugin needs to check to see if auto-subdomain www is checked. If it is it should request a certificate for it.

LE doesn't issue wildcards certificates. So not sure how to handle the \* option.

**Comment by alexalouit** [comment]
You're right.
I wrote a patch to fix that, I commit it in the day.

**Comment by alexalouit** [comment]
See 7508d70198192aba9678d7dedc446a1ecb127d8b
