### ISSUE TITLE
404 on nginx

### ISSUE THREAD

**Issue by awlx** [alexalouit/ISPConfig-letsencrypt#22]
Hi,

it seems that the .well-known folder does not get created in the correct way or the vhost lags the entry when the Cert is requested.

I have debug logging enabled and there are no errors in the ispconfig.log. But the letsencrypt log says "404".

Would be very nice if you can help.

On my other hosts with Apache2 everything works without any problem.

Cheers

**Comment by awlx** [comment]
It seems there is an issue with the default nginx config generate by ispconfig for each host. There is the following thing:
  location ~ /. {
       deny all;
       access_log off;
       log_not_found off;
   }

And it seems to always match and deny the access.

**Comment by alexalouit** [comment]
How did you install the plugin?

Nginx template must be replaced by https://github.com/alexalouit/ISPConfig-letsencrypt/blob/ISPConfig-3.0.5.4p8/src/server/conf/nginx_vhost.conf.master

`rsync -av ./src/ /usr/local/ispconfig/` command (manual installation or automatic) should do it.

**Comment by awlx** [comment]
Seems this didn't work out with the install script. A manual copy resolved the problem. Thx!

**Comment by alexalouit** [comment]
Weird.. Merge function for files is same for all.
Did you change the file before? Maybe is it a permission problem?
Do you know what is the old file permission?

**Comment by awlx** [comment]
Well the patch for the nginx.conf had also to be applied manually. Maybe it's a CentOS6 specific problem. Where somethings do not match the expectations. I can have a look this evening at another system which is not Letsencrypt-enabled yet.

Thanks for your help! And for your awesome work :).

**Comment by awlx** [comment]
It was not a default permission problem, on the other host it worked without a problem. So maybe something special on this host.

I close it now. Thx.
