### ISSUE TITLE
SNI support

### ISSUE THREAD

**Issue by zenny** [alexalouit/ISPConfig-letsencrypt#24]
Hi,

Kudos for the script.

Just wondering whether this script support SNI-based domains (single public IP multiple domains under ISPconfig3)?.

Thanks.

**Comment by awlx** [comment]
I have only one IP and 5 domains, works without any problem.

**Comment by alexalouit** [comment]
This script don't affect SNI.
See ISPConfig configuration (and apache/nginx).
