### ISSUE TITLE
Alias domains

### ISSUE THREAD

**Issue by zenny** [alexalouit/ISPConfig-letsencrypt#25]
Hi,

Alias domains (pointing several domains to a single site) seems to be not working at least for me.

If I missed something, kindly give me a pointer.

Thanks!

**Comment by alexalouit** [comment]
Yes, it's in todo list file.
Let me some days to see that.

**Comment by zenny** [comment]
Thanks for your work, Alex. aliasdomain support is very important as most of the people point their .org, .net domains to .com or vice versa like lestencrypt.com.

**Comment by Gorbov** [comment]
+1 for alias!
It's very important

**Comment by alexalouit** [comment]
fix in 73b52f7d2bbe5ef267384afe79115d19ec98ca7e
