### ISSUE TITLE
Renewal frequency too high

### ISSUE THREAD

**Issue by a-v-s** [alexalouit/ISPConfig-letsencrypt#27]
When I look at the cronjob created by ISPConfig-letsencrypt, 
`30 02 * * * /root/.local/share/letsencrypt/bin/letsencrypt-renewer >> /var/log/ispconfig/cron.log; done
`
This will renew the certificate every night at half past two. 
https://community.letsencrypt.org/t/rate-limits-for-lets-encrypt/6769 states:

> Certificates/Domain you could run into through repeated re-issuance. This limit measures certificates issued for a given combination of Public Suffix + Domain (a "registered domain"). This is limited to 5 certificates per domain per week.

This means you're exceeding the limit as renewing every night would request 7 certificates per domain per week.

**Comment by plutocrat** [comment]
Its possible the script is self aware and although it runs once a day, it keeps track of when it last did an update (eg touch last-run.dat ) and only actually runs a lot less often. 
But probably once on the first of each month would be ample in the crontab 
30  02  01  \*  \* 
Or every other month:
30  02  01 2,4,6,8,10,12  \* 
But I don't know what the script is actually doing, so maybe the developer will comment.

**Comment by zenny** [comment]
@alexalouit @a-v-s @plutocrat 

In view of LEs limit of 5 certs/domain/week, isn't it good to run crontab once a week or month? I meant

Instead of:

> 30 02 \* \* \* /root/.local/share/letsencrypt/bin/letsencrypt-renewer >> /var/log/ispconfig/cron.log; done

Replace with something like either to run 1st of every month:

> 30 02 01 \* \* /root/.local/share/letsencrypt/bin/letsencrypt-renewer >> /var/log/ispconfig/cron.log; done

Or every week on saturday:

> 30 02 \* \* sat /root/.local/share/letsencrypt/bin/letsencrypt-renewer >> /var/log/ispconfig/cron.log; done

??

**Comment by a-v-s** [comment]
The new renewer includes a freshness check. Therefore this should is no longer an issue.
