### ISSUE TITLE
"$lddomain" should be without "--domains"

### ISSUE THREAD

**Issue by Questler** [alexalouit/ISPConfig-letsencrypt#3]
This should be without "--domains"(apache2_plugin.inc.php:956 & :959):

$lddomain = (string) "--domains $domain";
            if($data['new']['subdomain'] == "www" OR $data['new']['subdomain'] == "*") {
                $lddomain .= (string) " --domains www." . $domain;
            }

**Comment by alexalouit** [comment]
fix in cde1917d97281b7e162719de477bf4b65a823491
