### ISSUE TITLE
Malformed crontab command?

### ISSUE THREAD

**Issue by plutocrat** [alexalouit/ISPConfig-letsencrypt#35]
Hi,
Just noticed that I get errors when the crontab command executes:
30 02 \* \* \* /root/.local/share/letsencrypt/bin/letsencrypt-renewer >> /var/log/ispconfig/cron.log; done
Malformed expression. 
Removing "; done" from the end of the command allows it to run, and the messages appear in cron.log now.

**Comment by alexalouit** [comment]
fix in 2a9b20e
