### ISSUE TITLE
jose+json

### ISSUE THREAD

**Issue by MZorzy** [alexalouit/ISPConfig-letsencrypt#4]
as here
https://community.letsencrypt.org/t/using-the-webroot-domain-verification-method/1445/29?u=nemis
in the 2 patch files "jose+json" need to change to "text/plain"

for me work this directive . in nginx snipplets
location /.well-known/acme-challenge {
    location ~ /.well-known/acme-challenge/(.*) {
    allow all;
    add_header Content-Type "text/plain";
    }
}

**Comment by alexalouit** [comment]
fix in 125e1d95edf71a6c8ac7b14348dc26eccd2a7a97
