### ISSUE TITLE
How to uninstall before update to ISPConfig 3.1

### ISSUE THREAD

**Issue by lewie** [alexalouit/ISPConfig-letsencrypt#42]
I want to update a Server to ISPConfig 3.1. How should I uninstall ISPConfig-letsencrypt?

Thanks

**Comment by alexalouit** [comment]
ISPConfig 3.1 use same code. No need to uninstall at this time (just remove crontab line).
(be careful, ISPConfig 3.1 is in beta version, and many things don't works correctly)
