### ISSUE TITLE
alias domain produce a none.domain

### ISSUE THREAD

**Issue by cchris-org** [alexalouit/ISPConfig-letsencrypt#48]
Set an Alias to a Domain and select "none" on auto subdomain.
It will generate a none.aliasDomain.xx wich could not verify by letsencrypt

my solution in apache2_plugin.inc work for me.

if(isset($aliasdomain['subdomain']) && ! empty($aliasdomain['subdomain'])) {
  // .. we dont like "none.aliasdomain"
  if($aliasdomain['subdomain'] != "none"){
      $temp_domains[] = $aliasdomain['subdomain'] . "." . $aliasdomain['domain'];
  }
}

**Comment by loeken** [comment]
faced the same issue, i simply created a records for none.* aswell

**Comment by loeken** [comment]
same solution also works for editing the nginx_plugin.inc

**Comment by alexalouit** [comment]
fix in #52
