### ISSUE TITLE
Certificate Creation Guide

### ISSUE THREAD

**Issue by petsoukos** [alexalouit/ISPConfig-letsencrypt#51]
It's all fine with the installation steps. (You could also add how to uninstall this patch)

But then what ?

I see the checkboxes SSL & Let's Encrypt. I enabled both and I don't see anything new now. How do you go about creating a Cert with Let's Encrypt?

Do we have to use the SSL tab ? Should a new tab appear (eg. Let's Encrypt) ??
If you have to use the SSL Tab... what should someone enter in the State, Locality, Organisation, etc fields? I tried to create a cert, but ended up not being a valid one, so I guess this isn't how you create the certs.

**Comment by sstratford** [comment]
And what is if there is an old cert created from ispconfig? Delete it ?

Am Mittwoch, den 27.04.2016, 12:21 -0700 schrieb petsoukos:

**Comment by alexalouit** [comment]
No need to go to SSL tab, just check let's encrypt checkbox, save and wait.
If it doesn't work, you have to debug.

**Comment by petsoukos** [comment]
Thanks for replying. I had to figure it out. That's why I was confused. Just add in the installation isntructions, that after the install Just mark the checkbox ;)

**Comment by alexalouit** [comment]
This is already in.
