### ISSUE TITLE
Can't install it

### ISSUE THREAD

**Issue by fatmaddin2000** [alexalouit/ISPConfig-letsencrypt#55]
Hi!

I am running ISConfig 3.0.5.4p9 on a Debian Wheezy.

If I folow your instructions and try to make the install script go I got: 

`ERROR: Let's Encrypt ( /root/.local/share/letsencrypt/bin/letsencrypt ) is missing, install it corecctly!`

If I try to get it insalled manually. I couldn't get any further after: `a2enconf letsencrypt`

It states: `-bash: a2enconf: Kommando nicht gefunden.` - it's german for "command not found"

Do you have any advice?

All the best! Thanks a lot for your work for this community.

**Comment by alexalouit** [comment]
Hi,
Let's Encrypt is installed? If is it, where is the binary file?

a2enconf command create symlink from / etc/apache2/conf-available to
/etc/apache2/conf-enabled, which is a switch for enable/disable
configuration file

If you want to do this manually, you can do this:

cd /etc/apache2/conf-enabled && ln -s ../conf-available/letsencrypt.conf
./letsencrypt.conf

then, restart apache
Hope this work..

**Comment by fatmaddin2000** [comment]
Hi!

Thanks a lot. I am getting closer. Now there is the "Let's encrypt" checkbox in ispConfig. I tried to activate it for one domain/website and there is no success. After pressing save in the website options I get a code there:

`#0 db->query(UPDATE`web_domain`SET`server_id`= '1',`ip_address`= 'MY.IP.ADD.RESS',`ipv6_address`= '',`domain`= 'my.domain',`type`= 'vhost',`parent_domain_id`= '0',`vhost_type`= 'name',`hd_quota`= '-1',`traffic_quota`= '-1',`cgi`= 'y',`ssi`= 'y',`suexec`= 'y',`errordocs`= '1',`subdomain`= 'www',`ssl`= 'y',`ssl_letsencrypt`= 'y',`php`= 'fast-cgi',`fastcgi_php_version`= '',`perl`= 'n',`ruby`= 'y',`python`= 'n',`active`= 'y' WHERE 1 AND domain_id = 4) called at [/usr/local/ispconfig/interface/lib/classes/tform_actions.inc.php:177] #1 tform_actions->onUpdateSave(UPDATE`web_domain`SET`server_id`= '1',`ip_address`= 'MY.IP.ADD.RESS',`ipv6_address`= '',`domain`= 'my.domain',`type`= 'vhost',`parent_domain_id`= '0',`vhost_type`= 'name',`hd_quota`= '-1',`traffic_quota`= '-1',`cgi`= 'y',`ssi`= 'y',`suexec`= 'y',`errordocs`= '1',`subdomain`= 'www',`ssl`= 'y',`ssl_letsencrypt`= 'y',`php`= 'fast-cgi',`fastcgi_php_version`= '',`perl`= 'n',`ruby`= 'y',`python`= 'n',`active`= 'y' WHERE 1 AND domain_id = 4) called at [/usr/local/ispconfig/interface/lib/classes/tform_actions.inc.php:117] #2 tform_actions->onUpdate() called at [/usr/local/ispconfig/interface/lib/classes/tform_actions.inc.php:94] #3 tform_actions->onSubmit() called at [/usr/local/ispconfig/interface/web/sites/web_domain_edit.php:798] #4 page_action->onSubmit() called at [/usr/local/ispconfig/interface/lib/classes/tform_actions.inc.php:68] #5 tform_actions->onLoad() called at [/usr/local/ispconfig/interface/web/sites/web_domain_edit.php:1098] Unknown column 'ssl_letsencrypt' in 'field list'`

I replaced my Domain and my IP address in this. What's wrong with my installation?

Thanks a lot in advance.

**Comment by alexalouit** [comment]
Copy all files are in src, (i suspect src/interface/web/sites/form/web_domain.tform.php missing).
Be sure to update your database.

Complete manual installation procedure is described in readme.

**Comment by fatmaddin2000** [comment]
I re-installed the cert-bot and now it seems to work. Thanks a lot.

**Comment by alexalouit** [comment]
great.
