### ISSUE TITLE
Bundle file link not created

### ISSUE THREAD

**Issue by blue-hound** [alexalouit/ISPConfig-letsencrypt#9]
Just installed the latest patch and if the bundle file exists in the sites SSL directory it is removed and the symlink is not created when enabling Lets Encrypt on a site. Apache SSLCACertificateFile is not added to vhost (related to file not existing?)

If the file doesn't exist when LE is enabled in the site then the symlink isn't created either.

**Comment by blue-hound** [comment]
I have a fix in pull request #10. The SSLCACertificateFile directive is added correctly to the vhost when the file exists as well. 

First time using GitHub, hopefully done correctly :-)

**Comment by alexalouit** [comment]
That's perfect!
